{"abstract":[{"text":"Retry button. When user will tap it call will try to reconnect.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"retryButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/retryButton","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callerrorview\/retrybutton"]},{"paths":["\/documentation\/talksdk\/callerrorview\/retrybutton"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@TalkSDK@objc(pl)CallErrorView(py)retryButton","role":"symbol","title":"retryButton","navigatorTitle":[{"kind":"identifier","text":"retryButton"}],"roleHeading":"Instance Property","modules":[{"name":"TalkSDK"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"retryButton","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":"!"}],"symbolKind":"property"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/retryButton":{"navigatorTitle":[{"kind":"identifier","text":"retryButton"}],"abstract":[{"text":"Retry button. When user will tap it call will try to reconnect.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/retryButton","title":"retryButton","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callerrorview\/retrybutton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"retryButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier","text":"UIButton"},{"kind":"text","text":"!"}],"required":true,"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"title":"CallErrorView","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","url":"\/documentation\/talksdk\/callerrorview","navigatorTitle":[{"text":"CallErrorView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represent the error view with "},{"code":"retry","type":"codeVoice"},{"type":"text","text":" and "},{"code":"cancel","type":"codeVoice"},{"text":" buttons.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"retryButton","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"retryButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":" * ","kind":"text"},{"text":"retryButton","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1retryButton\/title","value":"retryButton"},{"value":[{"kind":"identifier","text":"retryButton"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1retryButton\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title","value":"CallErrorView","op":"replace"},{"value":[{"kind":"identifier","text":"CallErrorView"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}